### ISSUE TITLE
OSX: Clicking on dock icon when closed via top left

### ISSUE THREAD

**Issue by jammehcow** [Meadowcottage/devRant#7]
When closing the window via the buttons at the top left of the window and clicking the devRant app icon following the close it throws the error:

```
A JavaScript error occurred in the main process

Uncaught Exception:
ReferenceError: createWindow is not defined
    at EventEmitter.<anonymous> (/Applications/devRant.app/Contents/Resources/app.asar/main.js:149:3)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
```

Global - make it global.

**Comment by Meadowcottage** [comment]
This issue has now been fixed.
